### ISSUE TITLE
Cannot find libmsoc.lib for Linux

### ISSUE THREAD

**Issue by matheuscmpm** [herumi/msoffice#1]
Hi, 

Where can we find this libmsoc for linux? The python sample only works at Windows, right? 

Hope you still have it :)

**Comment by herumi** [comment]
What purpose do you want to use libmsoc?
The command line tool `bin/msoffice-crypt.exe` runs well on Linux and you can call it by Python such as https://github.com/herumi/msoffice/blob/master/test_all.py .
How about it?

**Comment by matheuscmpm** [comment]
Hi,

Thanks for replying. I am building a module in my client's system and we
have to import a lot of xls files that are generated by their bank. All
this files are workbook encrypted, but we know all those passwords. We just
need a way to import these files, decrypt them, parse their content and
save to our database.

We did everything considering that the file wasn't protected, so our client
has to "Save as" their spreadsheets without password... but doing this
manually is not our ideal scenario. We are trying to find a solution to
this case and I found that possibly your lib could help us reach this goal.

I didn't knew that we could use the msoffice-cryp.exe inside linux. I have
compiled it under linux but I thought that I only could use .exe files
inside windows. And I tried to do so, but I kept getting this error:
"exception:ms:GetContentsByName:name:EncryptedPackage".

Thanks again for your attention.

Regards,

M. Melo

**Comment by herumi** [comment]
I'm sorry for the misleading name `msoffice-crypt.exe` and not to be able to help your work.

> "exception:ms:GetContentsByName:name:EncryptedPackage".

This error occurs if the format is not expected.
My tool supports only Microsoft Office 2010 or later format having suffix xlsx.
Are your xls files created by old Excel?

**Comment by matheuscmpm** [comment]
Dont worry about that, just for replying my messages you already saved me a
lot of time.

I double checked my files now, they are "Microsoft Excel 97-2003 Worksheet
(.xls)". That it is what is describe in the file properties.  So, I guess
that I can't use your tool for this purpose.

Do you have any past experience to unlock old excel files? I just need to
convert them in batch removing the password, and as I said, I have all
those passwords, so I am trying to run away from brute force solutions.

Thanks again for all this attention.

Best wishes.

Regards,

M. Melo

**Comment by herumi** [comment]
Do you need to execute the conversion on Linux?
I think to use VBA script if you can do it on Windows.
For example, by https://github.com/herumi/msoffice/blob/master/misc/decrypt-xls.vbs

```
>decrypt-xls.vbs <pass> <encrypted xls> <decrypted xls>
```

**Comment by matheuscmpm** [comment]
That's the ideal scenario for my application, which will be hosted on a
linux server - I was thinking about all this procedure being executed after
my client upload his spreasheets, that's what I have planned, but if I
could not solve this issue, I will probably have to develop some VBA
application or maybe Java/Python using LibreOffice API, that maybe work at
linux as well.

Did you already had any past experience with this API?

http://api.libreoffice.org/docs/idl/ref/interfacecom_1_1sun_1_1star_1_1script_1_1XLibraryContainerPassword.html#details

Don't know if can solve my problem.

Thanks again for being so kind and helpful answering my questions.

Regards,

M. Melo

**Comment by herumi** [comment]
I did not use LibreOffice API, but it seems not to be difficult according to [C++ examples](http://api.libreoffice.org/examples/examples.html#Cpp_examples).
