### ISSUE TITLE
fatal error: openssl/hmac.h: No such file or directory

### ISSUE THREAD

**Issue by uendelrocha** [herumi/msoffice#21]
**system specification**
> Ubuntu 20.04.2 LTS 64-bit
> gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
> clang version 10.0.0-4ubuntu1 
> Target: x86_64-pc-linux-gnu
> Thread model: posix

**installed successfully**
> ```
> mkdir work
> git clone https://github.com/herumi/cybozulib
> git clone https://github.com/herumi/msoffice
> make -j RELEASE=1
> ```

**error messages**
> In file included from /home/uendelrocha/Software/msoffice-crypt/msoffice/include/decode.hpp:14,
>                  from msoffice-crypt.cpp:16:
> /home/uendelrocha/Software/msoffice-crypt/msoffice/../cybozulib/include/cybozu/crypto.hpp:23:10: fatal error: openssl/hmac.h: No such file or directory
>    23 | #include <openssl/hmac.h>
>       |          ^~~~~~~~~~~~~~~~
> compilation terminated.
> make[1]: *** [../common.mk:57: release/msoffice-crypt.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> In file included from /home/uendelrocha/Software/msoffice-crypt/msoffice/include/attack.hpp:14,
>                  from attack.cpp:14:
> /home/uendelrocha/Software/msoffice-crypt/msoffice/../cybozulib/include/cybozu/crypto.hpp:23:10: fatal error: openssl/hmac.h: No such file or directory
>    23 | #include <openssl/hmac.h>
>       |          ^~~~~~~~~~~~~~~~
> compilation terminated.
> make[1]: *** [../common.mk:57: release/attack.o] Error 1
> make: *** [Makefile:7: all] Error 2
> 

**output messages file**
> [error.txt](https://github.com/herumi/msoffice/files/5940037/error.txt)

**Comment by herumi** [comment]
Please type `sudo apt install libssl-dev`.
