### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by oldpink** [herumi/msoffice#22]
I am having trouble compiling the latest git pulldown of msoffice, getting the following error each time that I attempt it:
/root/Downloads/msoffice/msoffice/../cybozulib/include/cybozu/file.hpp:300:32: error: ‘std::ios::seek_dir’ has not been declared
  300 |         void seek(int64_t pos, std::ios::seek_dir dir)
      |                                ^~~
In file included from attack.cpp:10:
/root/Downloads/msoffice/msoffice/../cybozulib/include/cybozu/file.hpp:300:32: error: ‘std::ios::seek_dir’ has not been declared
  300 |         void seek(int64_t pos, std::ios::seek_dir dir)

Fortunately, I already have compiled this excellent program from an earlier pulldown, but it would still be nice to be able to continue to build new revisions.

**Comment by herumi** [comment]
What compiler and OS do you use?
I can compile it on both gcc/Linux and visual studio/Windows.

**Comment by oldpink** [comment]
Slackware 14.2 (with Current updates) using gcc 11.1.0 and kernel/headers v 5.12.9.

**Comment by herumi** [comment]
Thank you for the information. I've fixed herumi/cybozulib. Could you please update it and recompile herumi/msoffice?

**Comment by oldpink** [comment]
Just did a git update and recompiled.
You are correct...success.
Thank you!
