### ISSUE TITLE
Add support for libssl3

### ISSUE THREAD

**Issue by floriangosse** [herumi/msoffice#24]
I've tried to run the tool on Ubuntu 22.04 but I wasn't able run it. It requires `libssl1.1` which isn't available anymore on this Ubuntu version.

**Comment by herumi** [comment]
I update https://github.com/herumi/cybozulib and remove the dependency to libssl.a.
Could you try it?

**Comment by tuky** [comment]
Thanks a lot, I just tried it on Ubuntu 22.4 (the binary with md5sum e4646cbf0ca9257bb35cc1f2fe342907 https://github.com/herumi/msoffice/blob/master/bin/msoffice-crypt.exe) and `./msoffice-crypt.exe --help` still fails with

```./msoffice-crypt.exe: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory```

I can see, that in https://github.com/herumi/msoffice/commit/a229101029cea829f7155df508e3bf9e7a5526d9 you removed one of the `-lcrypto` flags, but actually it was there twice so one `-lcrypto` is still there.

**Comment by floriangosse** [comment]
Thanks @tuky for taking over.

**Comment by tuky** [comment]
I was able to compile it in ubuntu 22.4 with this docker builder image:

```dockerfile
FROM ubuntu:22.04

RUN apt-get update -y && apt-get install -y libssl-dev build-essential git

WORKDIR /root

RUN git clone https://github.com/herumi/cybozulib
RUN git clone https://github.com/herumi/msoffice

WORKDIR /root/msoffice

RUN make all
```

you can extract the binary from the resulting image by running

```sh
docker build --no-cache . -t msoffice && docker run --rm --entrypoint cat msoffice /root/msoffice/bin/msoffice-crypt.exe > ./msoffice-crypt.exe && docker rmi msoffice
```

**Comment by herumi** [comment]
>you removed one of the -lcrypto flags, but actually it was there twice so one -lcrypto is still there.

It is for not msoffice-crypt.exe but a minisample.

I removed `-lssl` from LDFLAGS at https://github.com/herumi/msoffice/commit/a229101029cea829f7155df508e3bf9e7a5526d9#diff-1d53751ddf3ffeb25cfe609c6bd28746651e23ea81d51fe582b0f635f0896e0dL10 .
https://github.com/herumi/msoffice/commit/a229101029cea829f7155df508e3bf9e7a5526d9#diff-1d53751ddf3ffeb25cfe609c6bd28746651e23ea81d51fe582b0f635f0896e0dL10
