### ISSUE TITLE
AES256 / sha512 with manually installed OpenSSL3

### ISSUE THREAD

**Issue by kqe** [herumi/msoffice#27]
On Redhat 7, I manually installed OpenSSL3, and edited CFLAGS and LDFLAGS in common.mk, so can compile and run this msoffice package with no problem.  But when trying "-encMode 1", it complains "exception:hassPassword:not support:sha512".  How can I resolve this?

**Comment by herumi** [comment]
I fixed it at https://github.com/herumi/msoffice/commit/195ce472b313075eaee275b270a2e5914de9f681 .
Could you try the latest version?

**Comment by kqe** [comment]
Cool that solved the problem.  Thank you very much!
