### ISSUE TITLE
Unable to compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by Okiharaherbst** [herumi/msoffice#28]
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)

Thanks for helping

<img width="865" alt="image" src="https://user-images.githubusercontent.com/82608903/224880401-3b5de28a-c860-43f8-bbbd-7bf40ccc1dec.png">

**Comment by herumi** [comment]
Your OpenSSL seems old.
How about adding `-DCYBOZU_USE_OPENSSL_NEW_HASH=0` to CFLAGS in common.mk?

```
diff --git a/common.mk b/common.mk
index 8e569cb..c877bdc 100644
--- a/common.mk
+++ b/common.mk
@@ -7,6 +7,7 @@ CFLAGS_OPT = -O2 -DNDEBUG
 CFLAGS_WARN=-Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith #-Wswitch-enum -Wstrict-aliasing=2
 CFLAGS = -g -D_FILE_OFFSET_BITS=64
 CFLAGS+=$(CFLAGS_WARN)
+CFLAGS+=-DCYBOZU_USE_OPENSSL_NEW_HASH=0
 LDFLAGS = -lcrypto
 UNAME_S=$(shell uname -s)
 ifeq ($(UNAME_S),Darwin)
```

**Comment by Okiharaherbst** [comment]
Thank you for the swift response. Spot on, this did the trick and I've now been able to compile.

That's indeed running an older version of OpenSSL.
