### ISSUE TITLE
bin/msocsample.py does not work on Linux

### ISSUE THREAD

**Issue by decalage2** [herumi/msoffice#3]
It looks like the code in bin/msocsample.py is only intended to run on Windows, because it imports ctypes.wintypes (see http://bugs.python.org/issue16396).

Would it be possible to make it more portable, or to show how to use the msoc library from Python on Linux?

Thanks, and keep up the good work!

**Comment by herumi** [comment]
I think it is easier to use `bin/msoffice-crypt.exe` by Python on Linux, then I don't provide a sample code to use msoc library for Linux.
Do you use not `bin/msoffice-crypt.exe` but `lib/libmsoc.a`?
Then, I'll make a sample code.
