### ISSUE TITLE
Fails with exception:bad allocation for large excel files

### ISSUE THREAD

**Issue by swidz** [herumi/msoffice#32]
Hi,

I am trying to encrypt excel files on Windows.
Managed to clone msoffice, cybozulib_ext, cybozulib repos and successfully  build using mk.bat

No issues with encoding smaller files.
I was testing with larger excel files 250 000 rows x 150 cols, all values are random generated strings saved in shared string table.
The xlsx file size is approx 770 Mb and 3.5Gb after unpacking

When run I get the exception:bad allocation.

```
D:\projects\msoffice\bin>msoffice-crypt.exe -p "password" -e -vv c:\test\test_002.xlsx c:\test\test_002_encrypted.xlsx
inFile=c:\test\test_002.xlsx, outFile=c:\test\test_002_encrypted.xlsx, mode=enc, encMode=0
exception:bad allocation
```

**Comment by herumi** [comment]
How much memory does your PC have? Do you build msofficecrypt.exe with 64-bit mode?
I think "bad allocation" means there was not enough memory.
