### ISSUE TITLE
Exception when attempting decrypt

### ISSUE THREAD

**Issue by 3Fingers** [herumi/msoffice#6]
Attempting to decrypt and getting the following message:

$ bin/msoffice-crypt.exe -p 5558 247.docx 247-decrypt.docx
inFile=247.docx, outFile=247-decrypt.docx, mode=view, encMode=0
exception:ms:cfb:validate:minorVersion == 0x3eu || minorVersion == 0x3bu:/home/user/work/msoffice/include/cfb.hpp:186

**Comment by herumi** [comment]
How did you make the file `247.docs`?(What version is Microsoft Office?)
Can you use gdb?
If you can use it, then could you type the following command?
```
make DEBUG=1
gdb --args bin/msoffice-crypt.exe -p 5558 247.docx 247-decrypt.docx
(gdb) b include/cfb.hpp:186
(gdb)r
Breakpoint 1, ms::cfb::Header::analyze (... cfb.hpp:186
186                     MS_ASSERT(minorVersion == 0x3eu || minorVersion == 0x3bu);
(gdb) p minorVersion
$1 = 62
(qdb) quit
```

**Comment by 3Fingers** [comment]
I didn’t make the file.  We received it as an email attachment and it contains a macro to drop ransomware on the system. I am developing a workflow for my team to pull the disassembled/deobfuscated VBA code from it for future exams and want to use msoffice-crypt as part of the workflow as a safe method of removing the password for the document.

The document’s metadata reports it was created by Word version 12, so Word 2007.

Not familiar with gdb.  I’ll give it a try.

**Comment by 3Fingers** [comment]
Here’s the terminal from gdb:
gdb --args bin/msoffice-crypt.exe -p 5558 247.docx 247-decrypt.docx

GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bin/msoffice-crypt.exe...done.

(gdb) b include/cfb.hpp:186
Breakpoint 1 at 0x411c21: file /home/user/work/msoffice/include/cfb.hpp, line 186.

(gdb) r
Starting program: /home/user/work/msoffice/bin/msoffice-crypt.exe -p 5558 247.docx 247-decrypt.docx
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
inFile=247.docx, outFile=247-decrypt.docx, mode=view, encMode=0

Breakpoint 1, ms::cfb::Header::analyze (this=0x7fffffffce80, 
    data=0x7ffff7fed000 "\320\317\021\340\241\261", <incomplete sequence \341>, dataSize=37376) at /home/tony/work/msoffice/include/cfb.hpp:186
186			MS_ASSERT(minorVersion == 0x3eu || minorVersion == 0x3bu);

(gdb) p minorVersion
$1 = 62

(gdb) quit
A debugging session is active.

	Inferior 1 [process 8203] will be killed.

Quit anyway? (y or n) y

**Comment by herumi** [comment]
I'm sorry for the late response and thank you for your report.

```
/home/tony/work/msoffice/include/cfb.hpp:186 186 MS_ASSERT(minorVersion == 0x3eu || minorVersion == 0x3bu);
(gdb) p minorVersion $1 = 62
```

0x3eu = 62 and minorVersion = 62, then it is strange that `MS_ASSERT(minorVersion == ...)` fails.
Could you give me the `247.docx` if it does not contain secret information?

**Comment by 3Fingers** [comment]
[247-1.zip](https://github.com/herumi/msoffice/files/1891352/247-1.zip)

Password is 247.doc.  Inside is the PW protected doc - 247.doc (it's really a docx).  Also a 247-unprotected where the password was removed with Password and a screen shot of Passware's findings.

**Comment by herumi** [comment]
Thank you for the file. Microsoft Defender detects 247-unprotected.doc is virus and has removed it.

The header of 247/247.doc has majorVersion=3 and minorVersion=33.
An encrypted XML document must have minorVersion=0x3e([MS-CFB](https://msdn.microsoft.com/ja-jp/library/dd942138.aspx)).

According to [CFBF header format](https://en.wikipedia.org/wiki/Compound_File_Binary_Format#CFBF_Header_format), it is an old Microsoft Office format.

My software does not support old Microsoft Office format.

**Comment by owiofwm2i** [comment]
yes, same question as me,how to decrypt that?

**Comment by herumi** [comment]
I don't investigate a tool which supports the old format. Could you try to do it by yourself?
